⭐Valorant Conference Page⭐ | README and Presentation
Rysth/Valorant-Conference-Page pull request #10
Opened 2023-06-28 19:31 UTC by Rysth

# 🏅 Features Implemented
_Project Requirements -> https://github.com/microverseinc/curriculum-html-css/blob/main/capstone/html_capstone.md_

List of things that were implemented based on the requirements:

- ✅ Customized the Content of my Page.
- ✅ Followed the Design Guidelines from the Behance Design.
- ✅ Used a CSS Framework called Bootstrap to maintain a design pattern.
- ✅ Built the Home & About page.
- ✅ Built the Mobile & Desktop version for each page.
- ✅ Added a Link in the menu to go to the About Page.
- ✅ Added a Logo in the menu to go to the Home Page.
- ✅ Opened the Navigation Menu when clicking on the hamburger button.
- ✅ Closed the Navigation Menu when clicking on the x button.
- ✅ Used JavaScript to add dynamically each Feature Speakers card.

_John Palacios_
_Microverse Student_

2023-06-28 20:06 UTC, Ofarouq310 reviewed
Hi @Rysth , ✋ 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## 🔴  Invalid Code Review Request

- You have submitted a `README` that does not include the `Future Features` section, kindly note that it is one of the mandatory sections that has to be included. Refer to the main [template](https://github.com/microverseinc/readme-template) to know where to add it.

- Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-28 22:07 UTC, Ofarouq310 requested changes
Hi @Rysth, ✋ 

Good job so far! 💪 
There are some issues that you still need to work on to go to the next project but you are almost there! 🥈 

![giphy](https://github.com/Rysth/Conference-Page/assets/102612396/5ab302a5-796a-4050-8b57-eec8e4ed5af7)

## Highlights
✅ Descriptive PR title & summary.
✅ Meaningful commit messages.
✅ PRofessional README file.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-28 22:07 UTC, Ofarouq310 commented on README.md
> +
- [x] One of the project requirements indicated that you have to give proper credit to the author of the design, kindly add it to your `README`.

  ![image](https://github.com/Rysth/Conference-Page/assets/102612396/9579c848-fea9-4a99-8b9c-011a3a76837a)

2023-06-28 22:07 UTC, Ofarouq310 commented on about.html
- [x] When you are on the `About` page, your navbar has to have a nav item that redirects the user to the `Home` page, so instead of having an `About` nav item, it should be `Home`, kindly fix this issue.

  ![image](https://github.com/Rysth/Conference-Page/assets/102612396/bacc37c4-5b8a-4c56-afcc-3904bc05a341)

2023-06-29 15:29 UTC, Rysth commented on README.md
> +
Thanks @Ofarouq310!

- Added the Acknowledge to the Design Author.

2023-06-29 15:31 UTC, Rysth commented on about.html
Thanks @Ofarouq310!

- Changed the `About` item by a link to the `Home` page.

2023-06-29 15:47 UTC, abdallahmalima approved these changes
Hi @Rysth , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Home page and About page.✔️
- Contain  navbar and footer.✔️
- Project deployed.✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-29 15:58 UTC, Rysth commented
> Hi @Rysth ,
> 
> Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉
> 
> ## Highlights
> * Home page and About page.✔️
> * Contain  navbar and footer.✔️
> * Project deployed.✔️
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-29 15:59 UTC, merged